name: Advent of Code 2023 - Run Tests
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.1.0
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.9.0
        with:
          arguments: test
      - name: Test Report
        uses: dorny/test-reporter@v1.7.0
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: JUnit Tests
          reporter: java-junit
          path: build/test-results/test/TEST-*.xml


